### ISSUE TITLE
[Bug]: Unable to install LunarVIM with NodeJS dependencies

### ISSUE THREAD

**Issue by albertas** [LunarVim/LunarVim#2114]
### Problem description

I have executed the installation script with sudo rights in Ubuntu 20.04:
`sudo bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### LunarVim version

stable, rolling

### Neovim version (>= 0.5)

v0.7.0-dev

### Relevant log output

```shell
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
/usr/local/bin/tree-sitter -> /usr/local/lib/node_modules/tree-sitter-cli/cli.js

> tree-sitter-cli@0.20.1 install /usr/local/lib/node_modules/tree-sitter-cli
> node install.js

Downloading https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.1/tree-sitter-linux-x64.gz
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'tree-sitter'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-cli@0.20.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-cli@0.20.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-24T20_32_05_387Z-debug.log
```
```


### Screenshots

_No response_

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by albertas** [comment]
Just now I saw the link in installation instructions, which solves the issue:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by albertas** [comment]
I have installed `nvm` nodejs package manager as recommended at https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
After installation I get these outputs:
```
$ node --version
v16.13.1
$ npm --version
8.1.2
$ bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
[ERROR]: Unable to find dependencies [yarn][ERROR]: Unable to find dependencies [npm]Please install any one of the dependencies and re-run the installer. Try: 
sudo apt install -y yarn
sudo apt install -y npm
```

**Comment by albertas** [comment]
So it seems that `nvm` (and `node` with `npm` installed with `nvm`) were installed for current user. I have installed those for the root user also, which changed the error log:
```
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..

added 34 packages, and audited 35 packages in 8s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0
npm notice Run npm install -g npm@8.3.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /root/.nvm/versions/node/v16.13.1/lib/node_modules/tree-sitter-cli
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! internal/modules/cjs/loader.js:638
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Cannot find module '/root/.nvm/versions/node/v16.13.1/lib/node_modules/tree-sitter-cli/install.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
npm ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR!     at startup (internal/bootstrap/node.js:283:19)
npm ERR!     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by albertas** [comment]
Probably the reason of previous error is that `tree-sitter-cli` was merged into `tree-sitter` repository. As stated at https://github.com/tree-sitter/tree-sitter-cli#tree-sitter-cli

**Comment by kylo252** [comment]
This was hopefully fixed in https://github.com/LunarVim/LunarVim/pull/2113. Let me know if you're still having problems with it otherwise.
