### ISSUE TITLE
gopls with build flags seems to break goimports formatter

### ISSUE THREAD

**Issue by zalegrala** [LunarVim/LunarVim#2288]
### Problem description

Hello, I recently started working on a new project in Go that includes build tags in the test files.  Mostly this means I need to add some configuration to gopls.

But when I use the following config to make the adjustment, `goimports` seems to stop formatting the files.  If I comment out the `lspconfig.gopls.setup` call, then the formatter starts working again.

```lua
local lspconfig = require("lspconfig")
lspconfig.gopls.setup({
	cmd = { "gopls" },
	settings = {
		gopls = {
			buildFlags = { "-tags=requires_docker" },
		},
	},
})

local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{ exe = "goimports", filetypes = { "go" } },
})
```

Have I don't something incorrectly here?  I tried making the update using the `:Nlspconfig gopls` also, but that didn't seem to have any effect, and I wasn't clear that I was editing the correct file.

### LunarVim version

1.0.0-23-g2fa176

### Neovim version (>= 0.6.1)

v0.6.1

### Operating system/version

Linux

### Relevant log output

```shell
null-ls: require("null-ls.health").check()
========================================================================
  - OK: goimports: the command "goimports" is executable.
  - OK: stylua: the command "stylua" is executable.
  - OK: black: the command "black" is executable.
  - OK: golangci_lint: the command "golangci-lint" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/zach/.config/nvim/init.vim
    - ADVICE:
      - :help |nvim-from-vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **node**: `v17.3.0`
  - OK: **Go**: `go version go1.17.6 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **python3**: `Python 3.9.9`
  - OK: **npm**: `8.4.1`
  - OK: **pip3**: `pip 21.3.1 from /home/zach/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pip (python 3.9)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - hcl            ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/zach/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/zach/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /home/zach/.pyenv/shims/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/zach/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/zach/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /home/zach/.pyenv/versions/3.9.9/bin/python3
  - ERROR: Command error (job=6, exit code 1): `'/home/zach/.pyenv/versions/3.9.9/bin/python3' -c 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; print(neovim.__file__)'` (in '/home/zach/Code/deployment_tools')
    stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>  File "/home/zach/.local/lib/python3.9/site-packages/neovim/__init__.py", line 5, in <module>    import pynvim  File "/home/zach/.local/lib/python3.9/site-packages/pynvim/__init__.py", line 9, in <module>    from pynvim.api import Nvim, NvimError  File "/home/zach/.local/lib/python3.9/site-packages/pynvim/api/__init__.py", line 7, in <module>    from pynvim.api.buffer import Buffer  File "/home/zach/.local/lib/python3.9/site-packages/pynvim/api/buffer.py", line 2, in <module>    from pynvim.api.common import Remote  File "/home/zach/.local/lib/python3.9/site-packages/pynvim/api/common.py", line 4, in <module>    from msgpack import unpackbModuleNotFoundError: No module named 'msgpack'
  - INFO: Python version: 3.9.9
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: /home/zach/.pyenv/versions/3.9.9/bin/python3 -m pip install pynvim

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v17.3.0
  - INFO: Nvim node.js host: /home/zach/.config/yarn/global//node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 4.10.0, latest: 4.10.1
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/zach/.cache/nvim/lsp.log
  - INFO: Log size: 49360 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"<C-\\>"**
  - INFO: rhs: `<Cmd>execute v:count . "ToggleTerm"<CR>`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **";h"**
  - INFO: rhs: `<Cmd>nohlsearch<CR>`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **";c"**
  - INFO: rhs: `<Cmd>BufferClose!<CR>`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **";z"**
  - INFO: rhs: `:lua require('telekasten').panel()<CR>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>)"**
  - INFO: rhs: `()<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>>"**
  - INFO: rhs: `<lt>><Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>B"**
  - INFO: rhs: `{}<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S><lt>"**
  - INFO: rhs: `<lt>><Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>a"**
  - INFO: rhs: `<lt>><Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>`"**
  - INFO: rhs: ```<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>{"**
  - INFO: rhs: `{}<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>b"**
  - INFO: rhs: `()<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>d"**
  - INFO: rhs: `""<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>}"**
  - INFO: rhs: `{}<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>q"**
  - INFO: rhs: `''<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>t"**
  - INFO: rhs: ```<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>("**
  - INFO: rhs: `()<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>\""**
  - INFO: rhs: `""<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>'"**
  - INFO: rhs: `''<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>["**
  - INFO: rhs: `[]<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>]"**
  - INFO: rhs: `[]<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>s"**
  - INFO: rhs: `[]<Left>`

```
```


### Screenshots

_No response_

**Comment by abzcoding** [comment]
if you want to override gopls, i would suggest adding it to override_list
```lua
-- ~/.config/lvim/config.lua
vim.list_extend(lvim.lsp.override, {  "gopls" })
```
and then creating a file called `~/.config/lvim/ftplugin/go.lua`
```lua
local opts = {
  settings = {
    gopls = {
      buildFlags = { "-tags=requires_docker" }, -- custom build flags
      gofumpt = true, -- A stricter gofmt
      codelenses = {
        gc_details = true, -- Toggle the calculation of gc annotations
        generate = true, -- Runs go generate for a given directory
        regenerate_cgo = true, -- Regenerates cgo definitions
        tidy = true, -- Runs go mod tidy for a module
        upgrade_dependency = true, -- Upgrades a dependency in the go.mod file for a module
        vendor = true, -- Runs go mod vendor for a module
      },
      diagnosticsDelay = "300ms",
      experimentalWatchedFileDelay = "100ms",
      symbolMatcher = "fuzzy",
      completeUnimported = true,
      staticcheck = true,
      matcher = "Fuzzy",
      usePlaceholders = true, -- enables placeholders for function parameters or struct fields in completion responses
      analyses = {
        fieldalignment = true, -- find structs that would use less memory if their fields were sorted
        nilness = true, -- check for redundant or impossible nil comparisons
        shadow = true, -- check for possible unintended shadowing of variables
        unusedparams = true, -- check for unused parameters of functions
        unusedwrite = true, -- checks for unused writes, an instances of writes to struct fields and arrays that are never read
      },
    },
  },
  on_attach = require("lvim.lsp").common_on_attach,
  on_init = require("lvim.lsp").common_on_init,
  capabilities = require("lvim.lsp").common_capabilities(),
}

local servers = require "nvim-lsp-installer.servers"
local server_available, requested_server = servers.get_server "gopls"
if server_available then
  opts.cmd_env = requested_server:get_default_options().cmd_env
end

require("lvim.lsp.manager").setup("gopls", opts)
```

**Comment by zalegrala** [comment]
That seems to work great.  Thank you for the example.

Did I miss some documentation about this?  With a number of plugins involved, I get a little confused about which plugin is handling which functionality.

**Comment by abzcoding** [comment]
no worries mate, [this part](https://www.lunarvim.org/languages/#server-setup) in documentation talks about this, though i do agree it can be a bit more clear maybe
