### ISSUE TITLE
How to configure LSP to recognize `htmldjango`

### ISSUE THREAD

**Issue by dycw** [LunarVim/LunarVim#2472]
### Problem description

In `htmldjango` files, I do not get the language server.

![Screenshot from 2022-04-15 13-24-28](https://user-images.githubusercontent.com/10572122/163524784-c7e9f3ea-de2b-45bb-b086-39ac4f2eadd7.png)

### LunarVim version

f92a0d6

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by linuxbrew@a1e553b903c7

### Operating system/version

Ubuntu 20.04 LTS

### Affected language servers

html

### Steps to reproduce

None needed I believe; this is an out-of-the-box behaviour I am trying to change.

### Actual behavior

In `htmldjango` files, I do not get the language server.

![Screenshot from 2022-04-15 13-24-28](https://user-images.githubusercontent.com/10572122/163524784-c7e9f3ea-de2b-45bb-b086-39ac4f2eadd7.png)

### Expected behavior

Activation of the `html` language server in `htmldjango` file types.

![Screenshot from 2022-04-15 13-30-38](https://user-images.githubusercontent.com/10572122/163525412-da1eb4ff-b4d1-4ed9-bb53-6be384fb866c.png)

### log and support info

```shell
`:LspInfo`:


Language client log: /home/derek/.cache/nvim/lsp.log
Detected filetype:   htmldjango

0 client(s) attached to this buffer:

Configured servers list:
```

`:LvimInfo`:

```
E5108: Error executing lua vim/shared.lua:218: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:218: in function 'func'
        vim/shared.lua:205: in function 'tbl_filter'
        .../derek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:105: in function 'make_override_info'
        .../derek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:153: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

`:messages`
```
E5108: Error executing lua vim/shared.lua:218: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:218: in function 'func'
        vim/shared.lua:205: in function 'tbl_filter'
        .../derek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:105: in function 'make_override_info'
        .../derek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:153: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua vim/shared.lua:218: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:218: in function 'func'
        vim/shared.lua:205: in function 'tbl_filter'
        .../derek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:105: in function 'make_override_info'
        .../derek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:153: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
```

`:checkhealth`:

```

null-ls: require("null-ls.health").check()
========================================================================
  - OK: stylua: the command "stylua" is executable.
  - OK: black: the command "black" is executable.
  - OK: isort: the command "isort" is executable.
  - OK: shfmt: the command "shfmt" is executable.
  - OK: prettier: the command "prettier" is executable.
  - OK: luacheck: the command "luacheck" is executable.
  - OK: flake8: the command "flake8" is executable.
  - OK: shellcheck: the command "shellcheck" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/derek/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: xterm-256color
  - INFO: default-terminal: tmux-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.30`
  - OK: **gzip**: `gzip 1.10`
  - OK: **curl**: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
  - OK: **wget**: `GNU Wget 1.20.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.0`
  - OK: **node**: `v17.9.0`
  - OK: **Ruby**: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]`
  - OK: **Go**: `go version go1.17.1 linux/amd64`
  - OK: **RubyGem**: `3.3.7`
  - OK: **npm**: `8.5.5`
  - OK: **pip3**: `pip 22.0.4 from /home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.9.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - bibtex         ✓ . ✓ ✓ .
  - scala          ✓ . ✓ . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - lua            ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - zig            ✓ . ✓ ✓ ✓
  - ocamllex       ✓ . . . ✓
  - ocaml_interface✓ ✓ ✓ . ✓
  - ocaml          ✓ ✓ ✓ . ✓
  - heex           ✓ ✓ ✓ ✓ ✓
  - eex            ✓ . . . ✓
  - svelte         ✓ . ✓ ✓ ✓
  - surface        ✓ . ✓ ✓ ✓
  - gleam          ✓ ✓ ✓ ✓ ✓
  - elixir         ✓ ✓ ✓ ✓ ✓
  - erlang         . . . . .
  - scss           ✓ . . ✓ .
  - godot_resource ✓ ✓ ✓ . .
  - css            ✓ . ✓ ✓ ✓
  - cooklang       ✓ . . . .
  - gdscript       ✓ ✓ . ✓ ✓
  - julia          ✓ ✓ ✓ ✓ ✓
  - sparql         ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - solidity       ✓ . . . .
  - kotlin         ✓ ✓ ✓ . ✓
  - jsdoc          ✓ . . . .
  - lalrpop        ✓ ✓ . . .
  - java           ✓ ✓ . ✓ ✓
  - comment        ✓ . . . .
  - php            ✓ ✓ ✓ ✓ ✓
  - vala           ✓ . . . .
  - norg           . . . . .
  - fish           ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - pascal         ✓ ✓ ✓ ✓ ✓
  - perl           ✓ . ✓ . .
  - ruby           ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ . . ✓
  - make           ✓ . . . ✓
  - graphql        ✓ . . ✓ ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - gowork         ✓ . . . ✓
  - teal           ✓ ✓ ✓ ✓ ✓
  - http           ✓ . . . ✓
  - gomod          ✓ . . . ✓
  - fennel         ✓ ✓ . . ✓
  - r              ✓ ✓ . ✓ .
  - rst            ✓ ✓ . . ✓
  - hocon          ✓ . . . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - dart           ✓ ✓ . ✓ ✓
  - hjson          ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - ledger         ✓ . ✓ ✓ ✓
  - ninja          ✓ . ✓ ✓ .
  - json5          ✓ . . . ✓
  - yang           ✓ . ✓ . .
  - rasi           ✓ ✓ ✓ ✓ .
  - rust           ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - prisma         ✓ . . . .
  - dockerfile     ✓ . . . ✓
  - latex          ✓ . ✓ . ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - beancount      ✓ . ✓ . .
  - vue            ✓ . ✓ ✓ ✓
  - llvm           ✓ . . . .
  - pug            ✓ . . . ✓
  - devicetree     ✓ ✓ ✓ ✓ ✓
  - glimmer        ✓ . . . .
  - turtle         ✓ ✓ ✓ ✓ ✓
  - commonlisp     ✓ ✓ ✓ . .
  - toml           ✓ ✓ ✓ ✓ ✓
  - regex          ✓ . . . .
  - clojure        ✓ ✓ ✓ . ✓
  - pioasm         ✓ . . . ✓
  - ql             ✓ ✓ . ✓ ✓
  - tlaplus        ✓ ✓ ✓ . ✓
  - dot            ✓ . . . ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - hcl            ✓ . ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - cmake          ✓ . ✓ . .
  - haskell        ✓ . . . ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - supercollider  ✓ ✓ ✓ ✓ ✓
  - fusion         ✓ ✓ ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: tmuxclipboard

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/derek/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/derek/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /home/derek/work/django-learning-web-development-with-django/.venv/bin/python is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/derek/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/derek/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3.9 in the environment.
  - WARNING: Your virtualenv is not set up optimally.
    - ADVICE:
      - Create a virtualenv specifically for Nvim and use `g:python3_host_prog`.  This will avoid the need to install the pynvim module in each virtualenv.
  - INFO: Executable: /home/linuxbrew/.linuxbrew/bin/python3.9
  - INFO: Python version: 3.9.12
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - WARNING: $VIRTUAL_ENV is set to: /home/derek/work/django-learning-web-development-with-django/.venv
    And its /bin directory contains: python, python3, python3.10, pythoni, pythoni1
    But $PATH yields this pythoni executable: Traceback (most recent call last):
    File "/home/derek/work/django-learning-web-development-with-django/.venv/bin/pythoni", line 30, in <module>
    from pyrepl.python_reader import main
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/python_reader.py", line 25, in <module>
    from pyrepl.completing_reader import CompletingReader
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/completing_reader.py", line 22, in <module>
    from pyrepl import commands, reader
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/commands.py", line 376, in <module>
    from pyrepl import input
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/input.py", line 39, in <module>
    from trace import trace
    ImportError: cannot import name 'trace' from 'trace' (/home/derek/.pyenv/versions/3.10.0/lib/python3.10/trace.py)

    And $PATH in subshells yields this pythoni executable: Traceback (most recent call last):
    File "/home/derek/work/django-learning-web-development-with-django/.venv/bin/pythoni", line 30, in <module>
    from pyrepl.python_reader import main
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/python_reader.py", line 25, in <module>
    from pyrepl.completing_reader import CompletingReader
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/completing_reader.py", line 22, in <module>
    from pyrepl import commands, reader
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/commands.py", line 376, in <module>
    from pyrepl import input
    File "/home/derek/work/django-learning-web-development-with-django/.venv/lib/python3.10/site-packages/pyrepl/input.py", line 39, in <module>
    from trace import trace
    ImportError: cannot import name 'trace' from 'trace' (/home/derek/.pyenv/versions/3.10.0/lib/python3.10/trace.py)

    And $PATH yields this pythoni1 executable:   File "/home/derek/work/django-learning-web-development-with-django/.venv/bin/pythoni1", line 16
    print 'Python', sys.version
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

    And $PATH in subshells yields this pythoni1 executable:   File "/home/derek/work/django-learning-web-development-with-django/.venv/bin/pythoni1", line 16
    print 'Python', sys.version
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

    So invoking Python may lead to unexpected results.
    - ADVICE:
      - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.
      - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/34996

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.9.0
  - INFO: Nvim node.js host: /home/linuxbrew/.linuxbrew/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

targets: health#targets#check
========================================================================
  - WARNING: Conflicting mapping found:
    a| → :<C-U>normal! F|vf|<CR>
    | → {'separator': [{'d': '|'}]}
  - WARNING: Conflicting mapping found:
    i| → :<C-U>normal! T|vt|<CR>
    | → {'separator': [{'d': '|'}]}

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `harpoon`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

## Telescope Extension: `repo`
  - OK: Will use `glow` to preview markdown READMEs
  - OK: Will use `bat` to preview non-markdown READMEs
  - ERROR: `cached_list` will not function without locate
  - OK: fd: found `fd`
    fd 8.3.2
  - INFO: Repos found for `:Telescope repo list`:
    ...

## Telescope Extension: `zoxide`
  - INFO: No healthcheck provided

telescope._extensions.repo: require("telescope._extensions.repo.health").check()
========================================================================
  - OK: Will use `glow` to preview markdown READMEs
  - OK: Will use `bat` to preview non-markdown READMEs
  - ERROR: `cached_list` will not function without locate
  - OK: fd: found `fd`
    fd 8.3.2
  - INFO: Repos found for `:Telescope repo list`:
    ...

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/derek/.cache/nvim/lsp.log
  - INFO: Log size: 1089 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for beancount: ABI version 13
  - OK: Loaded parser for bibtex: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for clojure: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for commonlisp: ABI version 13
  - OK: Loaded parser for cooklang: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for cuda: ABI version 13
  - OK: Loaded parser for dart: ABI version 13
  - OK: Loaded parser for devicetree: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for dot: ABI version 13
  - OK: Loaded parser for eex: ABI version 13
  - OK: Loaded parser for elixir: ABI version 13
  - OK: Loaded parser for erlang: ABI version 13
  - OK: Loaded parser for fennel: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for fusion: ABI version 13
  - OK: Loaded parser for gdscript: ABI version 13
  - OK: Loaded parser for gleam: ABI version 13
  - OK: Loaded parser for glimmer: ABI version 13
  - OK: Loaded parser for glsl: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for godot_resource: ABI version 13
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for gowork: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for haskell: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for heex: ABI version 13
  - OK: Loaded parser for hjson: ABI version 13
  - OK: Loaded parser for hocon: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for http: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for jsdoc: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for json5: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for julia: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for lalrpop: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for ledger: ABI version 13
  - OK: Loaded parser for llvm: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for ninja: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for norg: ABI version 13
  - OK: Loaded parser for ocaml: ABI version 13
  - OK: Loaded parser for ocaml_interface: ABI version 13
  - OK: Loaded parser for ocamllex: ABI version 13
  - OK: Loaded parser for pascal: ABI version 13
  - OK: Loaded parser for perl: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for pioasm: ABI version 13
  - OK: Loaded parser for prisma: ABI version 13
  - OK: Loaded parser for pug: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ql: ABI version 13
  - OK: Loaded parser for query: ABI version 13
  - OK: Loaded parser for r: ABI version 13
  - OK: Loaded parser for rasi: ABI version 13
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rst: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for solidity: ABI version 13
  - OK: Loaded parser for sparql: ABI version 13
  - OK: Loaded parser for supercollider: ABI version 13
  - OK: Loaded parser for surface: ABI version 13
  - OK: Loaded parser for svelte: ABI version 13
  - OK: Loaded parser for teal: ABI version 13
  - OK: Loaded parser for tlaplus: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for turtle: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vala: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for yang: ABI version 13
  - OK: Loaded parser for zig: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"v"**, lhs: **" n"**
  - INFO: rhs: `:NR<CR>`
  - WARNING: conflicting keymap exists for mode **"v"**, lhs: **"a"**
  - INFO: rhs: `targets#e('o', 'a', 'a')`
  - WARNING: conflicting keymap exists for mode **"v"**, lhs: **"i"**
  - INFO: rhs: `targets#e('o', 'i', 'i')`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[C"**
  - INFO: rhs: `<Plug>(unimpaired-string-encode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[u"**
  - INFO: rhs: `<Plug>(unimpaired-url-encode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[y"**
  - INFO: rhs: `<Plug>(unimpaired-string-encode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[x"**
  - INFO: rhs: `<Plug>(unimpaired-xml-encode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]C"**
  - INFO: rhs: `<Plug>(unimpaired-string-decode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]u"**
  - INFO: rhs: `<Plug>(unimpaired-url-decode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]y"**
  - INFO: rhs: `<Plug>(unimpaired-string-decode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]x"**
  - INFO: rhs: `<Plug>(unimpaired-xml-decode)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"<SNR>94_"**
  - INFO: rhs: `<SNR>94_`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"ys"**
  - INFO: rhs: `<Plug>Ysurround`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"yS"**
  - INFO: rhs: `<Plug>YSurround`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"m"**
  - INFO: rhs: `:<C-U>call signature#utils#Input()<CR>`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gs"**
  - INFO: rhs: `<Plug>Lightspeed_gs`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>Lc"**
  - INFO: old rhs: `<CMD>edit /home/derek/.config/lvim/config.lua <CR>`
  - INFO: new rhs: `<cmd>edit /home/derek/.config/lvim/config.lua<cr>`
```
```


### Screenshots

_No response_

**Comment by abzcoding** [comment]
you have two options
1. use `html` lang server
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, {  "html" })
local opts = {
  filetypes = { "html", "htmldjango" }
}
require("lvim.lsp.manager").setup("html", opts)
```
---

2. use `tailwindcss` lang server
```lua
require("lvim.lsp.manager").setup("tailwindcss", opts)
```


---

also make sure that you are installing those language servers using
```vim
:LspInstall <server_name>
```

**Comment by abzcoding** [comment]
btw these are all from our documentation at https://www.lunarvim.org/languages/#server-setup

**Comment by dycw** [comment]
Thank you!

**Comment by abzcoding** [comment]
the language server should start automatically if any of these files are found in the root of your project
```lua

**Comment by dycw** [comment]
Hi @abzcoding ,

I just upgraded from Neovim 0.6 to 0.7. Suddenly, everything works:

![Screenshot from 2022-04-16 20-24-36](https://user-images.githubusercontent.com/10572122/163674884-45d02e9e-5d0e-48a3-9fd0-b15aeda09275.png)

**Comment by kobzar** [comment]
This variant isnt worked
`local opts = {
  root_dir = function(fname)
    return require("lspconfig").util.root_pattern ".git"(fname) or require("lspconfig").util.path.dirname(fname)
  end,
  filetypes = { "html", "htmldjango" }
}
require("lvim.lsp.manager").setup("tailwindcss", opts)`

So, i choose 
`require("lvim.lsp.manager").setup("html", opts)`
`
But i think we must make support htmldjango by default for python develop.
