### ISSUE TITLE
Install Failed on Alpine Linux

### ISSUE THREAD

**Issue by butterfly1924** [LunarVim/LunarVim#2634]
### Problem description

```
  checking whether Darwin os_unfair_lock_*() is compilable... no
  checking whether Darwin OSSpin*() is compilable... no
  checking whether glibc malloc hook is compilable... no
  checking whether glibc memalign hook is compilable... no
  checking whether pthreads adaptive mutexes is compilable... no
  checking whether compiler supports -D_GNU_SOURCE... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether strerror_r returns char with gnu source is compilable... no
  checking for stdbool.h that conforms to C99... yes
  checking for _Bool... yes
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating jemalloc.pc
  config.status: creating doc/html.xsl
  config.status: creating doc/manpages.xsl
  config.status: creating doc/jemalloc.xml
  config.status: creating include/jemalloc/jemalloc_macros.h
  config.status: creating include/jemalloc/jemalloc_protos.h
  config.status: creating include/jemalloc/jemalloc_typedefs.h
  config.status: creating include/jemalloc/internal/jemalloc_preamble.h
  config.status: creating test/test.sh
  config.status: creating test/include/test/jemalloc_test.h
  config.status: creating config.stamp
  config.status: creating bin/jemalloc-config
  config.status: creating bin/jemalloc.sh
  config.status: creating bin/jeprof
  config.status: creating include/jemalloc/jemalloc_defs.h
  config.status: creating include/jemalloc/internal/jemalloc_internal_defs.h
  config.status: creating test/include/test/jemalloc_test_defs.h
  config.status: executing include/jemalloc/internal/public_symbols.txt commands
  config.status: executing include/jemalloc/internal/private_symbols.awk commands
  config.status: executing include/jemalloc/internal/private_symbols_jet.awk commands
  config.status: executing include/jemalloc/internal/public_namespace.h commands
  config.status: executing include/jemalloc/internal/public_unnamespace.h commands
  config.status: executing include/jemalloc/internal/size_classes.h commands
  config.status: executing include/jemalloc/jemalloc_protos_jet.h commands
  config.status: executing include/jemalloc/jemalloc_rename.h commands
  config.status: executing include/jemalloc/jemalloc_mangle.h commands
  config.status: executing include/jemalloc/jemalloc_mangle_jet.h commands
  config.status: executing include/jemalloc/jemalloc.h commands
  ===============================================================================
  jemalloc version   : 0.0.0-0-g0000000000000000000000000000000000000000
  library revision   : 2

  CONFIG             : --disable-cxx --with-jemalloc-prefix=_rjem_ --with-private-namespace=_rjem_ --host=x86_64-alpine-linux-musl --build=x86_64-alpine-linux-musl --prefix=/tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out build_alias=x86_64-alpine-linux-musl host_alias=x86_64-alpine-linux-musl CC=cc 'CFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall' 'LDFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall' 'CPPFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall'
  CC                 : cc
  CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops
  SPECIFIED_CFLAGS   : -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall
  EXTRA_CFLAGS       : 
  CPPFLAGS           : -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall -D_GNU_SOURCE -D_REENTRANT
  CXX                : 
  CONFIGURE_CXXFLAGS : 
  SPECIFIED_CXXFLAGS : 
  EXTRA_CXXFLAGS     : 
  LDFLAGS            : -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall
  EXTRA_LDFLAGS      : 
  DSO_LDFLAGS        : -shared -Wl,-soname,$(@F)
  LIBS               : -lpthread
  RPATH_EXTRA        : 

  XSLTPROC           : false
  XSLROOT            : 

  PREFIX             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out
  BINDIR             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/bin
  DATADIR            : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/share
  INCLUDEDIR         : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/include
  LIBDIR             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/lib
  MANDIR             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/share/man

  srcroot            : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/jemalloc/
  abs_srcroot        : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/jemalloc/
  objroot            : 
  abs_objroot        : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/build/

  JEMALLOC_PREFIX    : _rjem_
  JEMALLOC_PRIVATE_NAMESPACE
                     : _rjem_je_
  install_suffix     : 
  malloc_conf        : 
  autogen            : 0
  debug              : 0
  stats              : 1
  prof               : 0
  prof-libunwind     : 0
  prof-libgcc        : 0
  prof-gcc           : 0
  fill               : 1
  utrace             : 0
  xmalloc            : 0
  log                : 0
  lazy_lock          : 0
  cache-oblivious    : 1
  cxx                : 0
  ===============================================================================
  running: "make" "srcroot=../jemalloc/" "-j" "2"

  --- stderr
  thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.2/build.rs:389:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
    Building [=================>         ] 55/81: clap                                                                                                           













### LunarVim version

Newest

### Neovim version (>= 0.7)

YES

### Operating system/version

Alpine Edge

### Steps to reproduce

_No response_

### support info

  checking whether Darwin os_unfair_lock_*() is compilable... no
  checking whether Darwin OSSpin*() is compilable... no
  checking whether glibc malloc hook is compilable... no
  checking whether glibc memalign hook is compilable... no
  checking whether pthreads adaptive mutexes is compilable... no
  checking whether compiler supports -D_GNU_SOURCE... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... yes
  checking whether strerror_r returns char with gnu source is compilable... no
  checking for stdbool.h that conforms to C99... yes
  checking for _Bool... yes
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating jemalloc.pc
  config.status: creating doc/html.xsl
  config.status: creating doc/manpages.xsl
  config.status: creating doc/jemalloc.xml
  config.status: creating include/jemalloc/jemalloc_macros.h
  config.status: creating include/jemalloc/jemalloc_protos.h
  config.status: creating include/jemalloc/jemalloc_typedefs.h
  config.status: creating include/jemalloc/internal/jemalloc_preamble.h
  config.status: creating test/test.sh
  config.status: creating test/include/test/jemalloc_test.h
  config.status: creating config.stamp
  config.status: creating bin/jemalloc-config
  config.status: creating bin/jemalloc.sh
  config.status: creating bin/jeprof
  config.status: creating include/jemalloc/jemalloc_defs.h
  config.status: creating include/jemalloc/internal/jemalloc_internal_defs.h
  config.status: creating test/include/test/jemalloc_test_defs.h
  config.status: executing include/jemalloc/internal/public_symbols.txt commands
  config.status: executing include/jemalloc/internal/private_symbols.awk commands
  config.status: executing include/jemalloc/internal/private_symbols_jet.awk commands
  config.status: executing include/jemalloc/internal/public_namespace.h commands
  config.status: executing include/jemalloc/internal/public_unnamespace.h commands
  config.status: executing include/jemalloc/internal/size_classes.h commands
  config.status: executing include/jemalloc/jemalloc_protos_jet.h commands
  config.status: executing include/jemalloc/jemalloc_rename.h commands
  config.status: executing include/jemalloc/jemalloc_mangle.h commands
  config.status: executing include/jemalloc/jemalloc_mangle_jet.h commands
  config.status: executing include/jemalloc/jemalloc.h commands
  ===============================================================================
  jemalloc version   : 0.0.0-0-g0000000000000000000000000000000000000000
  library revision   : 2

  CONFIG             : --disable-cxx --with-jemalloc-prefix=_rjem_ --with-private-namespace=_rjem_ --host=x86_64-alpine-linux-musl --build=x86_64-alpine-linux-musl --prefix=/tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out build_alias=x86_64-alpine-linux-musl host_alias=x86_64-alpine-linux-musl CC=cc 'CFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall' 'LDFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall' 'CPPFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall'
  CC                 : cc
  CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops
  SPECIFIED_CFLAGS   : -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall
  EXTRA_CFLAGS       : 
  CPPFLAGS           : -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall -D_GNU_SOURCE -D_REENTRANT
  CXX                : 
  CONFIGURE_CXXFLAGS : 
  SPECIFIED_CXXFLAGS : 
  EXTRA_CXXFLAGS     : 
  LDFLAGS            : -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -Wall
  EXTRA_LDFLAGS      : 
  DSO_LDFLAGS        : -shared -Wl,-soname,$(@F)
  LIBS               : -lpthread
  RPATH_EXTRA        : 

  XSLTPROC           : false
  XSLROOT            : 

  PREFIX             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out
  BINDIR             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/bin
  DATADIR            : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/share
  INCLUDEDIR         : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/include
  LIBDIR             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/lib
  MANDIR             : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/share/man

  srcroot            : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/jemalloc/
  abs_srcroot        : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/jemalloc/
  objroot            : 
  abs_objroot        : /tmp/cargo-installQMpxpF/release/build/jemalloc-sys-3e834880eac559f4/out/build/

  JEMALLOC_PREFIX    : _rjem_
  JEMALLOC_PRIVATE_NAMESPACE
                     : _rjem_je_
  install_suffix     : 
  malloc_conf        : 
  autogen            : 0
  debug              : 0
  stats              : 1
  prof               : 0
  prof-libunwind     : 0
  prof-libgcc        : 0
  prof-gcc           : 0
  fill               : 1
  utrace             : 0
  xmalloc            : 0
  log                : 0
  lazy_lock          : 0
  cache-oblivious    : 1
  cxx                : 0
  ===============================================================================
  running: "make" "srcroot=../jemalloc/" "-j" "2"

  --- stderr
  thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.2/build.rs:389:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
    Building [=================>         ] 55/81: clap                                                                                                           

```

**Comment by abzcoding** [comment]
well it seems like your rust is failing to install the dependencies ([fd-find](https://github.com/sharkdp/fd) and [ripgrep](https://github.com/BurntSushi/ripgrep) )

you can install them manually and try again
also you can set `RUST_BACKTRACE=1` to see what is exactly causing their installation to fail

**Comment by kylo252** [comment]
I'm not sure that rust is fully supported yet on Alpine, see https://gitlab.alpinelinux.org/alpine/tsc/-/issues/21
You can skip the rust dependencies in the installer, and just install them manually, or maybe download their `musl` releases manually

- https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0
- https://github.com/sharkdp/fd/releases/tag/v8.3.2
