### ISSUE TITLE
segfault editing i915_pci.c

### ISSUE THREAD

**Issue by BobBeckett** [LunarVim/LunarVim#2655]
### Problem description

opening i915_pci.c from the linux kernel and scrolling down causes reliably reproducible segfault
file is available at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/gpu/drm/i915/i915_pci.c
or attached here.
[i915_pci.c.txt](https://github.com/LunarVim/LunarVim/files/8773942/i915_pci.c.txt)

`lvim i915_pci.c +646` will segfault with the following stacktrace observed via gdb:

```
(gdb) bt
#0  0x000055555575522d in ts_query_cursor_next_capture ()
#1  0x00005555555b527b in query_next_capture (L=0x7ffff7918380) at /home/runner/work/neovim/neovim/src/nvim/lua/treesitter.c:1082
#2  0x000055555577eef6 in lj_BC_FUNCC ()
#3  0x000055555576b4e8 in lua_pcall (L=L@entry=0x7ffff7918380, nargs=nargs@entry=4, nresults=nresults@entry=1, errfunc=errfunc@entry=-6) at lj_api.c:1116
#4  0x00005555555a9658 in nlua_pcall (lstate=0x7ffff7918380, nargs=4, nresults=1) at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:129
#5  0x00005555555b78ac in nlua_call_ref (ref=<optimized out>, name=<optimized out>, args=..., retval=<optimized out>, err=0x7fffffffc240) at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:1366
#6  0x00005555554f1f8a in decor_provider_invoke (ns_id=16, name=name@entry=0x5555557ee882 "line", ref=<optimized out>, args=..., default_true=default_true@entry=true, perr=perr@entry=0x555555b254d0 <provider_err>) at /home/runner/work/neovim/neovim/src/nvim/decoration_provider.c:26
#7  0x00005555554f2960 in providers_invoke_line (wp=0x555556ab8f20, providers=0x7fffffffda80, row=685, has_decor=0x7fffffffc502, err=0x555555b254d0 <provider_err>) at /home/runner/work/neovim/neovim/src/nvim/decoration_provider.c:131
#8  0x000055555565fbbc in win_line (wp=wp@entry=0x555556ab8f20, lnum=lnum@entry=686, startrow=startrow@entry=64, endrow=78, nochange=true, number_only=number_only@entry=false, foldinfo=..., providers=0x7fffffffda80) at /home/runner/work/neovim/neovim/src/nvim/screen.c:2188
#9  0x000055555566680b in win_update (wp=wp@entry=0x555556ab8f20, providers=providers@entry=0x7fffffffdb00) at /home/runner/work/neovim/neovim/src/nvim/screen.c:1538
#10 0x000055555566785e in update_screen (type=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/screen.c:583
#11 0x00005555555efa06 in normal_redraw (s=s@entry=0x7fffffffdbe0) at /home/runner/work/neovim/neovim/src/nvim/normal.c:1290
#12 0x00005555555f18a3 in normal_check (state=0x7fffffffdbe0) at /home/runner/work/neovim/neovim/src/nvim/normal.c:1381
#13 0x000055555569d5a2 in state_enter (s=0x7fffffffdbe0) at /home/runner/work/neovim/neovim/src/nvim/state.c:31
#14 0x00005555555eee05 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/normal.c:463
#15 0x00005555555bdd32 in main (argc=<optimized out>, argv=<optimized out>) at /home/runner/work/neovim/neovim/src/nvim/main.c:574
(gdb) info threads
  Id   Target Id                                 Frame 
* 1    Thread 0x7ffff7c1e740 (LWP 570800) "nvim" 0x000055555575522d in ts_query_cursor_next_capture ()
  2    Thread 0x7ffff7897700 (LWP 570821) "nvim" 0x00007ffff7d4749e in epoll_wait (epfd=16, events=events@entry=0x7ffff7893780, maxevents=maxevents@entry=1024, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  3    Thread 0x7ffff6518700 (LWP 570824) "nvim" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555b27ca8 <cond+40>) at ../sysdeps/nptl/futex-internal.h:183
  4    Thread 0x7ffff5d17700 (LWP 570825) "nvim" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555b27cac <cond+44>) at ../sysdeps/nptl/futex-internal.h:183
  5    Thread 0x7ffff5516700 (LWP 570826) "nvim" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555b27cac <cond+44>) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7ffff4d15700 (LWP 570827) "nvim" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555b27cac <cond+44>) at ../sysdeps/nptl/futex-internal.h:183

```

### LunarVim version

rolling-23df368

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Ubuntu 20.04.4 LTS

### Steps to reproduce

`lvim i915_pci.c +646`

### support info

```console
# :LspInfo
 Language client log: /home/bob/.cache/lvim/lsp.log
 Detected filetype:   c
 
 1 client(s) attached to this buffer: 
 
 Client: clangd (id: 1, pid: 1075270, bufnr: [1])
 	filetypes:       c, cpp, objc, objcpp
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             clangd
 
 Configured servers list: clangd
```

```console
# :LvimInfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                c
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      clangd
* id:                        1
* supported filetype(s):     [c, cpp, objc, objcpp]
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              astProvider              | typeHierarchyProvider     | documentFormattingProvider
			     clangdInlayHintsProvider | memoryUsageProvider       | documentRangeFormattingProvider
			     definitionProvider       | typeDefinitionProvider    | callHierarchyProvider
			     documentSymbolProvider   | selectionRangeProvider    | implementationProvider
			     referencesProvider       | hoverProvider             | declarationProvider
			     workspaceSymbolProvider  | documentHighlightProvider

Automatic LSP info
* Skipped servers: [ccls, sourcekit]

Formatters info
* Active: 
* Supported: [astyle, clang_format, uncrustify]

Linters info
* Active: 
* Supported: [cppcheck, gccdiag]

Code actions info
* Active: 
```

**Comment by sefricke** [comment]
I experience the same problem.

**Comment by opalmay** [comment]
Can't replicate, probably something fixed in lsp, Reopen this if issue persists
