### ISSUE TITLE
pre-commit not working on lvim terminal

### ISSUE THREAD

**Issue by grimgort** [LunarVim/LunarVim#2688]
### Problem description

Hello,

LunarVim makes pre-commit crash which works well in lunarvim dissocated terminals. virtualenv is correctly installed with python3.9

pre-commit : https://pre-commit.com

log :
````powershell
D:\ftarroux\Documents\FRED\BaseGit\matisse_fred>pre-commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to D:\ftarroux\AppData\Local\Temp\pre-commit\patch1654270854-19244.
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\_virtualenv.pt
h:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\distutils-prec
edence.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\_virtualenv.pt
h:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\distutils-prec
edence.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Traceback (most recent call last):
  File "d:\ftarroux\logiciel\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\ftarroux\logiciel\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\Scripts\clang-format.EXE\__main__.py", line 4, in <
module>
ImportError: cannot import name 'clang_format' from 'clang_format' (unknown location)

auto-formatter for modern fortran source code........(no files to check)Skipped
black................................................(no files to check)Skipped
gersemi..............................................(no files to check)Skipped
[INFO] Restored changes from D:\ftarroux\AppData\Local\Temp\pre-commit\patch1654270854-19244.

````

checkhealth neovim 
````
provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: D:\ftarroux\Logiciel\python39\python.EXE
  - INFO: Other python executable: D:/ftarroux/Logiciel/python39/python
  - INFO: Other python executable: D:/ftarroux/Logiciel/python38/python
  - INFO: Other python executable: D:/ftarroux/scoop/shims/python
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.3
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 7

## Python virtualenv
  - OK: no $VIRTUAL_ENV

````

### LunarVim version

1.1.3

### Neovim version (>= 0.7)

0.7

### Operating system/version

windows

### support info

                         
                             __                          _    ___         
                            / /   __  ______  ____ _____| |  / (_)___ ___ 
                           / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
                          / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
                         /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
                         
                         
                         Buffer info
                         * filetype:                lua
                         * bufnr:                   2
                         * treesitter status:       active
                         
                         Active client(s)
                         * name:                      sumneko_lua
                         * id:                        1
                         * supported filetype(s):     lua
                         * attached buffers:          2
                         * root_dir pattern:          2
                         * capabilities:              text_document_open_close | workspace_symbol | goto_definition
                                                      completion               | signature_help   | rename
                                                      document_highlight       | document_symbol  | execute_command
                                                      find_references          | hover            | type_definition
                         
                         
                         
                         Formatters info
                         * Active: stylua  
                         * Supported: [lua_format, stylua]
                         
                         Linters info
                         * Active: 
                         * Supported: [luacheck, selene]
                         
                         Code actions info
                         * Active:

**Comment by kylo252** [comment]
- does this work outside of neovim tho? I recommend using `pipx` to install `pre-commit`
- can you share your pre-commit-config.yml?

I've just tested this [configuration](https://github.com/LunarVim/LunarVim/blob/59361ebe7b677dea0ca490b989af89c8918e1618/.pre-commit-config.yaml#L17-L22) while only enabling Stylua, and it works fine for me

![image](https://user-images.githubusercontent.com/59826753/173063584-305888de-524f-4314-a31f-b04a55febe0a.png)

**Comment by grimgort** [comment]
the pre-commit works fine without lvim. it works fine with nvim-qt without the lvim config. I also removed my configuration file and my plugins. the bug persists.

just in case, my lvim configuration is here https://github.com/grimgort/lvim_config

I don't have my yml config immediately, but I use https://github.com/pre-commit/mirrors-clang-format

**Comment by Uzaaft** [comment]
What do you mean with dissocated terminals?

**Comment by Uzaaft** [comment]
I tested pre-commit in my lvim config, and everything works as expected.
Just to make sure that you've done everything correctly, have you installed the pre-commit script? I think for your case, it might be as little as just running:
```
pre-commit install
```
Inside your folder.

**Comment by grimgort** [comment]
> What do you mean with dissocated terminals?

With dissocied terminal (pwsh.exe )  it s work as expected... I re-run pre-commit install monday .

**Comment by grimgort** [comment]
bug persist.



````powershell
DATE : 13.06.2022 14:16:32
D:\ftarroux\Documents\FRED\BaseGit\matisse_fred [120-l-installeur-ne-demande-pas-de-repertoires-pour-la-bdd-user ≡ +0 ~4 -0 | +0 ~2 -0 !]> pre-commit inst
all
pre-commit installed at .git\hooks\pre-commit

DATE : 13.06.2022 14:16:37
D:\ftarroux\Documents\FRED\BaseGit\matisse_fred [120-l-installeur-ne-demande-pas-de-repertoires-pour-la-bdd-user ≡ +0 ~4 -0 | +0 ~2 -0 !]> pre-commit
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\_virtualenv.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\_virtualenv.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Traceback (most recent call last):
  File "d:\ftarroux\logiciel\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\ftarroux\logiciel\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ftarroux\AppData\Local\Temp\pre-commit\repoclhcvl0b\py_env-python3.9\Scripts\clang-format.EXE\__main__.py", line 4, in <module>
ImportError: cannot import name 'clang_format' from 'clang_format' (unknown location)

auto-formatter for modern fortran source code........(no files to check)Skipped
black................................................(no files to check)Skipped
gersemi..................................................................Failed
- hook id: gersemi
- exit code: 1

Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repowluwoyon\py_env-python3.9\lib\site-packages\_virtualenv.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repowluwoyon\py_env-python3.9\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repowluwoyon\py_env-python3.9\lib\site-packages\_virtualenv.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
Error processing line 1 of D:\ftarroux\AppData\Local\Temp\pre-commit\repowluwoyon\py_env-python3.9\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "d:\ftarroux\logiciel\python39\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'add_shim'

Remainder of file ignored
Traceback (most recent call last):
  File "d:\ftarroux\logiciel\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\ftarroux\logiciel\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ftarroux\AppData\Local\Temp\pre-commit\repowluwoyon\py_env-python3.9\Scripts\gersemi.EXE\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'gersemi.__main__'



```` 

.pre-commit-config.yaml :
````
exclude: ^intel/.*
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
        exclude: .*BDTO_MNT_global_f.h
-   repo: https://github.com/pseewald/fprettify/
    rev: 'v0.3.7'
    hooks:
    -   id: fprettify    
        files: .*.f90$|.*.F90$
-   repo: https://github.com/ambv/black
    rev: '22.3.0'
    hooks:
    - id: black
      language: python
      types: [python]
      # args: ["--line-length=120"]
      # cmake-format-precommit is not maintained
# -   repo: https://github.com/cheshirekow/cmake-format-precommit
#     rev: v0.6.13
#     hooks:
#     - id: cmake-format
-   repo: https://github.com/BlankSpruce/gersemi
    rev: 0.8.0
    hooks:
    - id: gersemi
````

**Comment by Uzaaft** [comment]
I am not able to reproduce the issue in a windows VM(note that I do not use virtualenv).
I think perhaps either:
The lunarvim terminal uses the wrong path/path variables, or it might spin up the cmd shell instead of powershell(both are just hypothesises)
My resources are limited, and I don't use windows, so I won't be looking into the issue myself.
You should add the [platform:windows](https://github.com/LunarVim/LunarVim/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aplatform%3Awindows) tag.

**Comment by grimgort** [comment]
I partially solved the problem. I deleted the python virtual environment directories from pre-commit (AppData\Local\Temp\pre-commit) and reinstalled pre-commit. Now it works. 

it's surprising that it only crashed with lunarvim and not in other terminals, or even vscode
