### ISSUE TITLE
Error while installing LunarVim's Python dependencies

### ISSUE THREAD

**Issue by A-tA-v** [LunarVim/LunarVim#3938]
### Problem description

Ubuntu 20.04, user: *root*
Installed virtual environment with Python 3.9 (system default is 3.8)
Launching Lunarvim installation *from* the activated Python 3.9 environment.
Got error message, which I cannot interpret, although Lunarvim works fine, at first glance.
Repeated installation several times (without wiping out the previous one) with the same result.
The problem is happening at the second optional point:
```
Would you like to install LunarVim's Python dependencies: pynvim?
```

This is how my .bashrc looks like after nvm and cargo installation. I installed nvm manually, not by apt.
```
.bashrc:
..........
MYPY="python3.9"
MYPIP="pip3.9"
alias py3="export PYTHONPATH=${PYTHONPATH}:. && ${MYPY} "
alias py3o="export PYTHONPATH=${PYTHONPATH}:. && ${MYPY} -O "
alias py3oo="export PYTHONPATH=${PYTHONPATH}:. && ${MYPY} -OO "
alias py3d="${MYPY} -m pdb -c 'import os, sys; sys.path.append(os.getcwd()); print(sys.path)' "
alias py3t="${MYPY} -m unittest "
alias py3dt="${MYPY} -m pdb -m unittest "
alias py3td="${MYPY} -m pdb -m unittest "
alias ipy="ipython "

alias pyqu=". ${HOME}/venv/qu/bin/activate"
alias deact="deactivate"

export PATH=${HOME}/.local/bin:${PATH}

. ${HOME}/venv/qu/bin/activate

. "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

-------------------------------------------------------
Btw, I have experienced another related issue but found a workaround on some forum:
```
# ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
# One quick fix is :
*. Go to the `pyvenv.cfg` file in the Virtual environment folder
*. Set the `include-system-site-packages` to `true` and save the change
*. Reactivate the virtual environment. This should work!
```
 

### LunarVim version

Stable Lunarvim 1.2

### Neovim version (>= 0.8.0)

Neovim 0.8.3

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

```
LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) : y
Verifying that pip is available..
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_internal/cli/main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_internal/exceptions.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 65, in <module>
  File "/tmp/tmprt80f_im/pip-20.0.2-py2.py3-none-any.whl/pip/_vendor/__init__.py", line 36, in vendored
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/lib/python3.9/ensurepip/__init__.py", line 266, in _main
    return _bootstrap(
  File "/usr/lib/python3.9/ensurepip/__init__.py", line 184, in _bootstrap
    return _run_pip(args + _PROJECTS, additional_paths)
  File "/usr/lib/python3.9/ensurepip/__init__.py", line 62, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/venv/qu/bin/python3', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmprt80f_im/setuptools-44.0.0-py2.py3-none-any.whl\', \'/tmp/tmprt80f_im/pip
-20.0.2-py2.py3-none-any.whl\', \'/tmp/tmprt80f_im/pkg_resources-0.0.0-py2.py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp
rt80f_im\', \'setuptools\', \'pip\', \'pkg_resources\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
Installing with pip..
Requirement already satisfied: pynvim in ./.local/lib/python3.9/site-packages (0.4.3)
Requirement already satisfied: greenlet in ./.local/lib/python3.9/site-packages (from pynvim) (2.0.2)
Requirement already satisfied: msgpack>=0.5.0 in ./.local/lib/python3.9/site-packages (from pynvim) (1.0.5)
All Python dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies: fd::fd-find, rg::ripgrep?
[y]es or [n]o (default: no) : y
All Rust dependencies are successfully installed
--------------------------------------------------------------------------------
Removing old packer cache file
--------------------------------------------------------------------------------
Backing up old /root/.config/lvim to /root/.config/lvim.old
--------------------------------------------------------------------------------
Backing up old /root/.local/share/lunarvim to /root/.local/share/lunarvim.old
--------------------------------------------------------------------------------
Backing up old /root/.cache/lvim to /root/.cache/lvim.old
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/root/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 17032, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 17032 (delta 86), reused 126 (delta 76), pack-reused 16882
Receiving objects: 100% (17032/17032), 13.83 MiB | 15.26 MiB/s, done.
Resolving deltas: 100% (10737/10737), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/root/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /root/.local/bin/lvim
make: Leaving directory '/root/.local/share/lunarvim/lvim'
Preparing Packer setup
Initializing first time setup
Installing packer
Cloning into '/root/.local/share/lunarvim/site/pack/packer/start/packer.nvim'...
Packer setup complete
--------------------------------------------------------------------------------
Verifying core plugins
Verification complete!
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Thank you for installing LunarVim!!
You can start it by running: /root/.local/bin/lvim
Do not forget to use a font with glyphs (icons) support [https://github.com/ryanoasis/nerd-fonts]
```

**Comment by A-tA-v** [comment]
I found a workaround advice at:
[github](https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check).
This works on Ubuntu 20.04, default Python 3.8, virtual environment.
```
pip3 install pyOpenSSL --upgrade
```

**Comment by kobzar** [comment]
This was not a LV issue. But this is good that you find the solution. 
Closed as finished.
