### ISSUE TITLE
LSP[puppet][Warning] An error occured while starting the Language Server. The server has been disabled.

### ISSUE THREAD

**Issue by techsk8** [LunarVim/LunarVim#4082]
### Problem description

![0](https://i.imgur.com/SufcOdZ.png)

I am trying to use the [puppet-editor-services](https://github.com/puppetlabs/puppet-editor-services) LSP and I'm getting the error that you see in the title. I've tried running the LSP manually and it works. 
```console
root@puppet-server:~/.local/share/lvim/mason/packages/puppet-editor-services# ./puppet-languageserver
LANGUAGE SERVER RUNNING localhost:37571

…

[mac@mac] ➜ bin ./puppet-languageserver
LANGUAGE SERVER RUNNING localhost:53529
```

I would really appreciate if this would work on `lunarvim` since I don't use other IDEs, besides `lunarvim / neovim`, and puppet lsp doesn't work on any of them.

I have bumped into this thing on both my Ubuntu 20.04 puppet-server and my MacOS 13 machine.
I have the same versions of `nvim` and `lunarvim` installed on both
Mention: I have built `neovim` from [source](https://github.com/LunarVim/nvim-basic-ide#install-neovim-09).

The interesting fact is that while yesterday I was getting this error which is tied to the puppet LSP:
```console
[START][2023-04-24 11:57:15] LSP logging initiated
   30 [ERROR][2023-04-24 11:57:15] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   29 [START][2023-04-24 11:57:42] LSP logging initiated
   28 [ERROR][2023-04-24 11:57:42] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   27 [ERROR][2023-04-24 11:59:03] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   26 [START][2023-04-25 03:48:29] LSP logging initiated
```

Today I'm not getting any error, only some other irrelevant errors coming from bashls regarding my .bashrc

Regarding the logs: on my Ubuntu 20.04 instance I have ruby installed from apt:
```console
root@puppet-server:~/production# ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
``` 

And on the macOS I'm using rvm
```console
[mac@mac] ➜ ~ rvm list
   ruby-2.7.6 [ arm64 ]
   ruby-2.7.8 [ arm64 ]
   ruby-3.0.0 [ arm64 ]
=* ruby-3.2.2 [ arm64 ]

# => - current
# =* - current && default
#  * - default

[mac@mac] ➜ ~ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
```

### LunarVim version

release-1.3/neovim-0.9-f74046d1

### Neovim version (>= 0.8.0)

NVIM v0.9.1-dev-46+gdeec5e6e2

### Operating system/version

macOS 13 && Ubuntu 20.04

### Affected language servers

puppet-editor-services

### Steps to reproduce

1. lvim test.pp 
2. The LSP will be installed automatically
3. And whenever you open a `.pp` file the LSP will get disabled for some reason, see the error I pasted

### Actual behavior

It doesn't work.

### Expected behavior

To work, nothing more or less.

### support info

LspInfo
```console
Press q or <Esc> to close this window. Press <Tab> to view server doc.
Language client log: /root/.local/state/lvim/lsp.log
Detected filetype:   puppet

Client: puppet (id: 1, bufnr: [1])
  filetypes:        puppet
  autostart:       true
  root directory:  /etc/puppetlabs/code/environments/production/modules/motd
  cmd:              puppet-languageserver --stdio

 Configured servers list: puppet
```

LvimInfo
```console

Buffer info:
  * filetype:                puppet  
  * bufnr:                   1                      
  * treesitter status:       inactive     
  
Active client(s)
   * name:                      puppet   
   * id: 
   * supported filetype(s):     puppet
   * attached buffers:          1
   * root_dir pattern:          1 

 Automatic LSP info 
   * Skipped servers: [angularls, ansiblels, antlersls, csharp_ls, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint,│
  
Formatters info
   * Active: 
   * Supported: puppet_lint 

Linters info
   * Active:    
   * Supported: puppet_lint
Code actions info
  * Active:
```

### logs

```console
The interesting fact is that while yesterday I was getting this error which is tied to the puppet LSP:

[START][2023-04-24 11:57:15] LSP logging initiated
   30 [ERROR][2023-04-24 11:57:15] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   29 [START][2023-04-24 11:57:42] LSP logging initiated
   28 [ERROR][2023-04-24 11:57:42] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   27 [ERROR][2023-04-24 11:59:03] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   26 [START][2023-04-25 03:48:29] LSP logging initiated
```

Today I'm not getting any error, only some other irrelevant errors coming from bashls regarding my .bashrc:

```console
[START][2023-04-25 04:06:37] LSP logging initiated
    3 [WARN][2023-04-25 04:06:37] ...lsp/handlers.lua:537 "04:06:37.735 WARNING ⛔️ file:///root/.bashrc line 104: non-constant source not supported"
    4 [WARN][2023-04-25 04:06:37] ...lsp/handlers.lua:537 "04:06:37.735 WARNING ⛔️ Error while parsing file:///root/.bashrc: syntax error"
    5 [WARN][2023-04-25 04:06:45] ...lsp/handlers.lua:537 "04:06:45.712 WARNING ⛔️ file:///root/.bashrc line 103: non-constant source not supported"
    6 [WARN][2023-04-25 04:06:45] ...lsp/handlers.lua:537 "04:06:45.712 WARNING ⛔️ Error while parsing file:///root/.bashrc: syntax error"
    7 [WARN][2023-04-25 04:06:47] ...lsp/handlers.lua:537 "04:06:47.910 WARNING ⛔️ file:///root/.bashrc line 102: non-constant source not supported"
    8 [WARN][2023-04-25 04:06:47] ...lsp/handlers.lua:537 "04:06:47.910 WARNING ⛔️ Error while parsing file:///root/.bashrc: syntax error"
```

### Screenshots
![1](https://i.imgur.com/SufcOdZ.png)

![2](https://i.imgur.com/8PoAdq1.png)

**Comment by techsk8** [comment]
I just found a workaround that made it all work for now, but the main issue is not yet fixed, as `Mason` will still install a bad package next time or when an update is performed.

![1](https://i.imgur.com/miyfd33.png)

What I did, is as follows:

## On the Ubuntu 20.04 machine:
Note: I had the package installed previously with Mason.
* I went to `~/.local/share/lvim/mason/packages`  and I removed the original LSP installed by `:Mason` everything with
```console
root@puppet-server:~/.local/share/lvim/mason/packages# ll
total 44
drwxr-xr-x 11 root root 4096 Apr 25 05:44 ./
drwxr-xr-x  7 root root 4096 Apr 24 03:20 ../
drwxr-xr-x  3 root root 4096 Apr 24 03:22 ansible-language-server/
drwxr-xr-x  3 root root 4096 Apr 24 03:31 awk-language-server/
drwxr-xr-x  3 root root 4096 Apr 24 05:51 azure-pipelines-language-server/
drwxr-xr-x  3 root root 4096 Apr 24 03:31 bash-language-server/
drwxr-xr-x  3 root root 4096 Apr 24 03:36 prettier/
drwxr-xr-x 10 root root 4096 Apr 25 06:09 puppet-editor-services/
drwxr-xr-x 11 root root 4096 Apr 24 03:31 ruby-lsp/
drwxr-xr-x  3 root root 4096 Apr 24 03:23 vim-language-server/
drwxr-xr-x  3 root root 4096 Apr 24 03:45 yaml-language-server/
root@puppet-server:~/.local/share/lvim/mason/packages# rm -rf puppet-editor-services/
```

Then I just followed the official instructions from [here](https://github.com/puppetlabs/puppet-editor-services.git)

* Clone this repository

```console
git clone https://github.com/puppetlabs/puppet-editor-services.git

cd puppet-editor-services
```

* Bundle the development gems

```console
bundle install

  ... < lots of text >
```

* Install the vendored gems

```console
bundle exec rake gem_revendor

  ... < lots of text >
```

Then I went into lvim and started the LSP with :LspStart and it worked right away.


## On the Mac 

I had to go in here: `/Users/<YOURUSER>/.local/share/nvim/mason/packages`

```console
[mac@mac] ➜ packages rm -rf puppet-editor-services
[mac@mac] ➜ packages git clone https://github.com/puppetlabs/puppet-editor-services.git
Cloning into 'puppet-editor-services'...
remote: Enumerating objects: 5548, done.
remote: Counting objects: 100% (395/395), done.
remote: Compressing objects: 100% (227/227), done.
remote: Total 5548 (delta 174), reused 346 (delta 162), pack-reused 5153
Receiving objects: 100% (5548/5548), 1.82 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (3396/3396), done.
[mac@mac] ➜ packages cd puppet-editor-services
[mac@mac] ➜ puppet-editor-services [ main] bundle install

[!] There was an error parsing `Gemfile`: undefined method `exists?' for File:Class. Bundler cannot continue.

 #  from /Users/mac/.local/share/nvim/mason/packages/puppet-editor-services/Gemfile:45
 #  -------------------------------------------
 #  # Evaluate Gemfile.local if it exists
 >  if File.exists? "#{__FILE__}.local"
 #    eval(File.read("#{__FILE__}.local"), binding)
 #  -------------------------------------------
[mac@mac] ➜ puppet-editor-services [ main] rvm list
   ruby-2.7.6 [ arm64 ]
   ruby-2.7.8 [ arm64 ]
   ruby-3.0.0 [ arm64 ]
=* ruby-3.2.2 [ arm64 ]

# => - current
# =* - current && default
#  * - default

[mac@mac] ➜ puppet-editor-services [ main] rvm use ruby-3.0.0
Using /Users/mac/.rvm/gems/ruby-3.0.0
[mac@mac] ➜ puppet-editor-services [ main] bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Using bundler 2.2.3
Fetching hocon 1.4.0
Fetching ast 2.4.2
Fetching deep_merge 1.2.2
.
.
.
Bundle complete! 17 Gemfile dependencies, 41 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from minitar:
The `minitar` executable is no longer bundled with `minitar`. If you are
expecting this executable, make sure you also install `minitar-cli`.

[mac@mac] ➜ puppet-editor-services [ main] bundle exec rake gem_revendor
Clearing the vendor directory...
Vendoring puppet-lint...
git clone https://github.com/puppetlabs/puppet-lint.git /Users/mac.local/share/nvim/mason/packages/puppet-editor-services/vendor/puppet-lint
Cloning into '/Users/mac/.local/share/nvim/mason/packages/puppet-editor-services/vendor/puppet-lint'...
remote: Enumerating objects: 10326, done.
remote: Counting objects: 100% (1347/1347), done.
remote: Compressing objects: 100% (592/592), done.
remote: Total 10326 (delta 735), reused 1213 (delta 658), pack-reused 8979
Receiving objects: 100% (10326/10326), 2.04 MiB | 8.21 MiB/s, done.
Resolving deltas: 100% (6018/6018), done.
git fetch origin
git reset --hard 2.5.2
HEAD is now at c362aa6 Merge pull request #25 from puppetlabs/sanfrancrisko-patch-1
.
. < just more git clones >
.

[mac@mac] ➜ puppet-editor-services [ main] bundle exec ruby ./puppet-languageserver --debug=stdout
I, [2023-04-25T11:35:20.417604 #49903]  INFO -- : Language Server is v1.3.1
D, [2023-04-25T11:35:20.417631 #49903] DEBUG -- : Loading gems...
I, [2023-04-25T11:35:22.288518 #49903]  INFO -- : Using Puppet v7.24.0
I, [2023-04-25T11:35:22.288552 #49903]  INFO -- : Using Facter v4.3.1
D, [2023-04-25T11:35:22.288579 #49903] DEBUG -- : Detected additional puppet settings []
I, [2023-04-25T11:35:22.296997 #49903]  INFO -- : Initializing settings...
I, [2023-04-25T11:35:22.297329 #49903]  INFO -- : Starting RPC Server...
D, [2023-04-25T11:35:22.298494 #49903] DEBUG -- : Using TCP Server
D, [2023-04-25T11:35:22.300211 #49903] DEBUG -- : TCPSRV: Services running. Press ^C to stop
D, [2023-04-25T11:35:22.300276 #49903] DEBUG -- : TCPSRV: Will stop the server in 10 seconds if no connection is made.
D, [2023-04-25T11:35:22.300287 #49903] DEBUG -- : TCPSRV: Will stop the server when client disconnects
D, [2023-04-25T11:35:22.300238 #49903] DEBUG -- : TCPSRV: Started listening on localhost:56200.
LANGUAGE SERVER RUNNING localhost:56200
D, [2023-04-25T11:35:32.311369 #49903] DEBUG -- : TCPSRV: No connection has been received in 10 seconds.  Shutting down server.
D, [2023-04-25T11:35:32.311591 #49903] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-25T11:35:32.416828 #49903] DEBUG -- : TCPSRV: Stopped listening on localhost:56200
D, [2023-04-25T11:35:32.521837 #49903] DEBUG -- : TCPSRV: Started shutdown process. Press ^C to force quit.
D, [2023-04-25T11:35:32.521874 #49903] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-25T11:35:32.521884 #49903] DEBUG -- : TCPSRV: Waiting for workers to cycle down
I, [2023-04-25T11:35:32.521921 #49903]  INFO -- : Language Server exited.

```
And that's it, it worked on the Mac after that as well.

**Comment by techsk8** [comment]
UPDATE:

The workaround worked for 1 day and now I'm back to point zero and it's showing no logs…

I have it up and running again: What I had to do was to reinstall the gems using ruby 3.1.0
```console
root@puppet-server:~# rbenv global 3.1.0
root@puppet-server:~# rbenv version
3.1.0 (set by /root/.rbenv/version)
root@puppet-server:~# ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
```
So, if you have the 3.1.0 version or higher I presume, it will work
But you need to reinstall the ruby gems with that version that the LSP requires.


Otherwise I was getting this error
```console
root@puppet-server:~/.local/share/lvim/mason/bin# ./puppet-languageserver --debug=stdout
I, [2023-04-26T11:00:07.927392 #49710]  INFO -- : Language Server is v1.3.1
D, [2023-04-26T11:00:07.927472 #49710] DEBUG -- : Loading gems...
E, [2023-04-26T11:00:07.983464 #49710] ERROR -- : Error while loading a critical gem: cannot load such file -- puppet ["<internal:/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/root/.local/share/lvim/mason/packages/puppet-editor-services/lib/puppet_languageserver.rb:74:in `require_gems'", "/root/.local/share/lvim/mason/packages/puppet-editor-services/lib/puppet_languageserver.rb:215:in `init_puppet'", "./puppet-languageserver:14:in `<main>'"]
I, [2023-04-26T11:00:07.984240 #49710]  INFO -- : Starting RPC Server...
I, [2023-04-26T11:00:07.984305 #49710]  INFO -- : Configured the Language Server to use the Disabled Message Router
D, [2023-04-26T11:00:07.984326 #49710] DEBUG -- : Using TCP Server
D, [2023-04-26T11:00:08.010854 #49710] DEBUG -- : TCPSRV: Services running. Press ^C to stop
D, [2023-04-26T11:00:08.013460 #49710] DEBUG -- : TCPSRV: Will stop the server in 10 seconds if no connection is made.
D, [2023-04-26T11:00:08.013706 #49710] DEBUG -- : TCPSRV: Will stop the server when client disconnects
LANGUAGE SERVER RUNNING localhost:44471
D, [2023-04-26T11:00:08.011941 #49710] DEBUG -- : TCPSRV: Started listening on localhost:44471.
D, [2023-04-26T11:00:18.023997 #49710] DEBUG -- : TCPSRV: No connection has been received in 10 seconds.  Shutting down server.
D, [2023-04-26T11:00:18.024237 #49710] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:00:18.024374 #49710] DEBUG -- : TCPSRV: Stopped listening on localhost:44471
D, [2023-04-26T11:00:18.024528 #49710] DEBUG -- : TCPSRV: Started shutdown process. Press ^C to force quit.
D, [2023-04-26T11:00:18.024659 #49710] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:00:18.024805 #49710] DEBUG -- : TCPSRV: Waiting for workers to cycle down
I, [2023-04-26T11:00:18.042659 #49710]  INFO -- : Language Server exited.
```

And now it all works
```console
root@puppet-server:~/.local/share/lvim/mason/packages/puppet-editor-services# ./puppet-languageserver --debug=stdout
I, [2023-04-26T11:01:38.772401 #49932]  INFO -- : Language Server is v1.3.1
D, [2023-04-26T11:01:38.772507 #49932] DEBUG -- : Loading gems...
I, [2023-04-26T11:01:39.837403 #49932]  INFO -- : Using Puppet v8.0.0
I, [2023-04-26T11:01:39.837475 #49932]  INFO -- : Using Facter v4.4.0
D, [2023-04-26T11:01:39.837583 #49932] DEBUG -- : Detected additional puppet settings []
I, [2023-04-26T11:01:39.851245 #49932]  INFO -- : Initializing settings...
I, [2023-04-26T11:01:39.852194 #49932]  INFO -- : Starting RPC Server...
D, [2023-04-26T11:01:39.852951 #49932] DEBUG -- : Using TCP Server
D, [2023-04-26T11:01:39.855072 #49932] DEBUG -- : TCPSRV: Services running. Press ^C to stop
D, [2023-04-26T11:01:39.856122 #49932] DEBUG -- : TCPSRV: Will stop the server in 10 seconds if no connection is made.
D, [2023-04-26T11:01:39.857739 #49932] DEBUG -- : TCPSRV: Will stop the server when client disconnects
LANGUAGE SERVER RUNNING localhost:35533
D, [2023-04-26T11:01:39.856053 #49932] DEBUG -- : TCPSRV: Started listening on localhost:35533.
D, [2023-04-26T11:01:49.869290 #49932] DEBUG -- : TCPSRV: No connection has been received in 10 seconds.  Shutting down server.
D, [2023-04-26T11:01:49.869540 #49932] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:01:49.869592 #49932] DEBUG -- : TCPSRV: Stopped listening on localhost:35533
D, [2023-04-26T11:01:49.869633 #49932] DEBUG -- : TCPSRV: Started shutdown process. Press ^C to force quit.
D, [2023-04-26T11:01:49.869680 #49932] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:01:49.869727 #49932] DEBUG -- : TCPSRV: Waiting for workers to cycle down
I, [2023-04-26T11:01:49.891129 #49932]  INFO -- : Language Server exited.
```

**Comment by mclarkson** [comment]
Thanks @techsk8 for the information as I was having the same error message, although my fix was different.

I had done `gem install puppet-lint` but not `gem install puppet`. After installing puppet mine worked.

This: '~/.local/share/lvim/mason/packages/puppet-editor-services# ./puppet-languageserver --debug=stdout', got me to the answer very quickly, thank you!
