### ISSUE TITLE
Fails to deploy using docker example given in docs

### ISSUE THREAD

**Issue by JonathanWilbur** [LunarVim/LunarVim#4320]
### Problem description

The `Try it first in Docker!` script on the installation page does not work.

### LunarVim version

latest

### Neovim version (>= 0.9.0)

latest

### Terminal name

Xfce Terminal

### Operating system/version

Debian bullseye/sid / Linux 5.15.0-78-generic #85~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

1. On [this page](https://www.lunarvim.org/docs/installation), run the `Try it first in Docker!` script.
2. The build fails, with the following logs:

### Screenshots

Even better than screenshots: logs.

```
docker run -w /tmp -it --rm alpine:edge sh -uelic 'addgroup -S lunaruser && adduser -S lunaruser -G lunaruser --shell /bin/sh && apk add yarn git python3 cargo neovim ripgrep alpine-sdk bash --update && LV_BRANCH='release-1.3/neovim-0.9' su -c "bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/release-1.3/neovim-0.9/utils/installer/install.sh)" lunaruser && su -c /home/lunaruser/.local/bin/lvim lunaruser'
Unable to find image 'alpine:edge' locally
edge: Pulling from library/alpine
9c87f2223d79: Pull complete 
Digest: sha256:2d01a16bab53a8405876cec4c27235d47455a7b72b75334c614f2fb0968b3f90
Status: Downloaded newer image for alpine:edge
sh: BASH_VERSION: parameter not set
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/83) Upgrading musl (1.2.3-r4 -> 1.2.4_git20230717-r2)
(2/83) Upgrading libcrypto3 (3.1.0-r2 -> 3.1.2-r0)
(3/83) Upgrading libssl3 (3.1.0-r2 -> 3.1.2-r0)
(4/83) Installing libattr (2.5.1-r5)
(5/83) Installing attr (2.5.1-r5)
(6/83) Installing libcap2 (2.69-r1)
(7/83) Installing libcap-getcap (2.69-r1)
(8/83) Installing fakeroot (1.32.1-r0)
(9/83) Installing libgcc (13.1.1_git20230722-r1)
(10/83) Installing libstdc++ (13.1.1_git20230722-r1)
(11/83) Installing lzip (1.23-r1)
(12/83) Installing openssl (3.1.2-r0)
(13/83) Installing patch (2.7.6-r10)
(14/83) Installing pkgconf (2.0.0-r0)
(15/83) Installing libacl (2.3.1-r4)
(16/83) Installing tar (1.35-r2)
(17/83) Installing ca-certificates (20230506-r0)
(18/83) Installing brotli-libs (1.0.9-r15)
(19/83) Installing c-ares (1.19.1-r1)
(20/83) Installing libunistring (1.1-r2)
(21/83) Installing libidn2 (2.3.4-r2)
(22/83) Installing nghttp2-libs (1.55.1-r0)
(23/83) Installing libcurl (8.2.1-r0)
(24/83) Installing curl (8.2.1-r0)
(25/83) Installing abuild (3.11.21-r0)
Executing abuild-3.11.21-r0.pre-install
(26/83) Installing jansson (2.14-r4)
(27/83) Installing zstd-libs (1.5.5-r7)
(28/83) Installing binutils (2.41-r0)
(29/83) Installing libmagic (5.45-r1)
(30/83) Installing file (5.45-r1)
(31/83) Installing libgomp (13.1.1_git20230722-r1)
(32/83) Installing libatomic (13.1.1_git20230722-r1)
(33/83) Installing gmp (6.3.0-r0)
(34/83) Installing isl26 (0.26-r1)
(35/83) Installing mpfr4 (4.2.0_p12-r0)
(36/83) Installing mpc1 (1.3.1-r1)
(37/83) Installing gcc (13.1.1_git20230722-r1)
(38/83) Installing libstdc++-dev (13.1.1_git20230722-r1)
(39/83) Installing musl-dev (1.2.4_git20230717-r2)
(40/83) Installing libc-dev (0.7.2-r5)
(41/83) Installing g++ (13.1.1_git20230722-r1)
(42/83) Installing make (4.4.1-r2)
(43/83) Installing fortify-headers (1.1-r3)
(44/83) Installing build-base (0.5-r3)
(45/83) Installing libexpat (2.5.0-r2)
(46/83) Installing pcre2 (10.42-r1)
(47/83) Installing git (2.41.0-r2)
(48/83) Installing alpine-sdk (1.0-r1)
(49/83) Installing ncurses-terminfo-base (6.4_p20230722-r0)
(50/83) Installing libncursesw (6.4_p20230722-r0)
(51/83) Installing readline (8.2.1-r2)
(52/83) Installing bash (5.2.15-r5)
Executing bash-5.2.15-r5.post-install
(53/83) Installing libffi (3.4.4-r3)
(54/83) Installing xz-libs (5.4.4-r0)
(55/83) Installing libxml2 (2.11.4-r0)
(56/83) Installing llvm16-libs (16.0.6-r6)
(57/83) Installing scudo-malloc (16.0.6-r1)
(58/83) Installing rust (1.71.1-r0)
(59/83) Installing cargo (1.71.1-r0)
(60/83) Installing libintl (0.22-r0)
(61/83) Installing luajit (2.1_p20230410-r3)
(62/83) Installing libuv (1.46.0-r0)
(63/83) Installing libluv (1.45.0.0-r0)
(64/83) Installing msgpack-c (6.0.0-r0)
(65/83) Installing unibilium (2.1.1-r0)
(66/83) Installing libtermkey (0.22-r1)
(67/83) Installing tree-sitter (0.20.10-r0)
(68/83) Installing libvterm (0.3.2-r0)
(69/83) Installing neovim (0.9.1-r0)
(70/83) Installing libbz2 (1.0.8-r6)
(71/83) Installing gdbm (1.23-r1)
(72/83) Installing mpdecimal (2.5.1-r2)
(73/83) Installing libpanelw (6.4_p20230722-r0)
(74/83) Installing sqlite-libs (3.42.0-r2)
(75/83) Installing python3 (3.11.4-r4)
(76/83) Installing python3-pycache-pyc0 (3.11.4-r4)
(77/83) Installing pyc (0.1-r0)
(78/83) Installing python3-pyc (3.11.4-r4)
(79/83) Installing ripgrep (13.0.0-r6)
(80/83) Installing icu-data-en (73.2-r2)
Executing icu-data-en-73.2-r2.post-install
*
* If you need ICU with non-English locales and legacy charset support, install
* package icu-data-full.
*
(81/83) Installing icu-libs (73.2-r2)
(82/83) Installing nodejs (18.17.0-r0)
(83/83) Installing yarn (1.22.19-r0)
Executing busybox-1.36.0-r5.trigger
Executing ca-certificates-20230506-r0.trigger
OK: 1097 MiB in 95 packages

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli?
[y]es or [n]o (default: no) : t
--------------------------------------------------------------------------------
Please answer [y]es or [n]o.
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli?
[y]es or [n]o (default: no) : y
Installing node modules with yarn..
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "neovim@4.10.1" with binaries:
      - neovim-node-host
success Installed "tree-sitter-cli@0.20.8" with binaries:
      - tree-sitter
Done in 4.71s.
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) : y
Verifying that pip is available..
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpg89gqyf_/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmpg89gqyf_/pip-23.1.2-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpg89gqyf_\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.

```

**Comment by LostNeophyte** [comment]
answer no to the dependencies

**Comment by JonathanWilbur** [comment]
This still is not fixed after doing that.
