### ISSUE TITLE
Trying out via docker fails

### ISSUE THREAD

**Issue by hemna** [LunarVim/LunarVim#4372]
### Problem description

1. Goto https://www.lunarvim.org/docs/installation
2. click Try it first in Docker!
3. Copy the docker run line
4. paste in shell.

docker run starts, packages are update and then installer asks if I want to install NodeJS dependencies.  That works,
then the installer asks If I want to install LunarVim's python dependencies: pynvim?  I said yes.
Install fails and docker container exits.

```
docker run -w /tmp -it --rm alpine:edge sh -uelic 'addgroup -S lunaruser && adduser -S lunaruser -G lunaruser --shell /bin/sh && apk add yarn git python3 cargo neovim ripgrep alpine-sdk bash --update && LV_BRANCH='release-1.3/neovim-0.9' su -c "bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/release-1.3/neovim-0.9/utils/installer/install.sh)" lunaruser && su -c /home/lunaruser/.local/bin/lvim lunaruser'
Unable to find image 'alpine:edge' locally
edge: Pulling from library/alpine
b790c763077d: Pull complete
Digest: sha256:f2d1645cd73c7e54584dc225da0b5229d19223412d719669ebda764f41396853
Status: Downloaded newer image for alpine:edge
sh: BASH_VERSION: parameter not set
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/80) Installing libattr (2.5.1-r5)
(2/80) Installing attr (2.5.1-r5)
(3/80) Installing libcap2 (2.69-r1)
(4/80) Installing libcap-getcap (2.69-r1)
(5/80) Installing fakeroot (1.32.1-r0)
...
...
...
(74/80) Installing pyc (0.1-r0)
(75/80) Installing python3-pyc (3.11.5-r0)
(76/80) Installing ripgrep (13.0.0-r6)
(77/80) Installing icu-data-en (73.2-r2)
Executing icu-data-en-73.2-r2.post-install
*
* If you need ICU with non-English locales and legacy charset support, install
* package icu-data-full.
*
(78/80) Installing icu-libs (73.2-r2)
(79/80) Installing nodejs (18.17.1-r0)
(80/80) Installing yarn (1.22.19-r0)
Executing busybox-1.36.1-r6.trigger
Executing ca-certificates-20230506-r0.trigger
OK: 1106 MiB in 95 packages

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli?
[y]es or [n]o (default: no) : yes
Installing node modules with yarn..
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "neovim@4.10.1" with binaries:
      - neovim-node-host
success Installed "tree-sitter-cli@0.20.8" with binaries:
      - tree-sitter
Done in 4.20s.
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) : yes
Verifying that pip is available..
error: externally-managed-environment

× This environment is externally managed
╰─>
    The system-wide python installation should be maintained using the system
    package manager (apk) only.

    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:

    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage

    To exit the virtual environment, run:

    deactivate

    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.

    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp3fyzagpa/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmp3fyzagpa/pip-23.2.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp3fyzagpa\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
[WARN]: skipping installing optional python dependencies
```

### LunarVim version

no idea

### Neovim version (>= 0.9.1)

no idea

### Terminal name

ssh

### Operating system/version

ubuntu

**Comment by LostNeophyte** [comment]
say no to installing dependencies in the installer

**Comment by hemna** [comment]
so no python support then?   I'm trying lunarvim simply to see the python support.

**Comment by LostNeophyte** [comment]
pynvim isn't necessary for python support

**Comment by CSRessel** [comment]
I took a look at the alpine environment for the install script, and it doesn't look like there's an easy way to user-install packages there without adding some exceptional behavior to the install script (which would be specific to the alpine environment). Instead, I thought it might be a better experience for trying out with docker, to skip the dependency install? That way no one is confused by a failed commands like the above

@LostNeophyte if that makes sense to you I proposed the docs changes here: https://github.com/LunarVim/lunarvim.org/pull/432
