### ISSUE TITLE
astro-language-server LSP Inactive

### ISSUE THREAD

**Issue by lesar** [LunarVim/LunarVim#4508]
### Problem description

astro-language-server is installed by Mason  
if I open index.astro on working project I get an error see screen shot

I'm new on lunarvim and do not know what to do so I try this:
`npm install -g @astrojs/language-server`
this not help  
and 
:LspInstall astro  
this not help  

I have search on other Issue but have not understand how to solve.  

is a bug or my mistake?  

best regards,
Leonardo

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Operating system/version

Fedora 39

### Affected language servers

astro

### Steps to reproduce

Open an *.astro file.  

### Actual behavior

the first time get the error, then LSP Inactive

### Expected behavior

LSP active

### support info

```console
:LspInfo
 Language client log: /home/leonardo/.local/state/lvim/lsp.log
 Detected filetype:   astro
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: astro
 
 Config: tailwindcss
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	root directory:    Not found.
 	cmd:               tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 Config: astro
 	filetypes:         astro
 	root directory:    /home/leonardo/Documenti/sviluppo/www/algoritmica.net/violet-giant
 	cmd:               astro-ls --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tailwindcss, astro

```

### logs

```console
[ERROR][2024-02-20 10:12:24] .../vim/lsp/rpc.lua:734	"rpc"	"astro-ls"	"stderr"	"/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45\n                readDirectory: modules.typescript.sys.readDirectory,\n                                                  ^\n\nTypeError: Cannot read properties of undefined (reading 'sys')\n    at Object.resolveConfig (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45:51)\n    at createProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/project.js:78:35)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:449:9)\n    at async getParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:302:29)\n    at async prepareClosestootParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:224:17)\n    at async findMatchConfigs (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:213:9)\n    at async Object.getProjectAndTsConfig [as getProject] (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:154:30)\n    at async getProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:314:17)\n    at async Immediate.<anonymous> (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:291:33)\n\nNode.js v20.9.0\n"
[WARN][2024-02-20 15:49:43] ...lsp/handlers.lua:137	"The language server astro triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2024-02-20 15:49:43] .../vim/lsp/rpc.lua:734	"rpc"	"astro-ls"	"stderr"	"/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45\n                readDirectory: modules.typescript.sys.readDirectory,\n                                                  ^\n\nTypeError: Cannot read properties of undefined (reading 'sys')\n    at Object.resolveConfig (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45:51)\n    at createProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/project.js:78:35)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:449:9)\n    at async getParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:302:29)\n    at async prepareClosestootParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:224:17)\n    at async findMatchConfigs (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:213:9)\n    at async Object.getProjectAndTsConfig [as getProject] (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:154:30)\n    at async getProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:314:17)\n    at async Immediate.<anonymous> (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:291:33)\n\nNode.js v20.9.0\n"
[WARN][2024-02-20 17:57:34] ...lsp/handlers.lua:137	"The language server astro triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2024-02-20 17:57:34] .../vim/lsp/rpc.lua:734	"rpc"	"astro-ls"	"stderr"	"/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45\n                readDirectory: modules.typescript.sys.readDirectory,\n                                                  ^\n\nTypeError: Cannot read properties of undefined (reading 'sys')\n    at Object.resolveConfig (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45:51)\n    at createProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/project.js:78:35)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:449:9)\n    at async getParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:302:29)\n    at async prepareClosestootParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:224:17)\n    at async findMatchConfigs (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:213:9)\n    at async Object.getProjectAndTsConfig [as getProject] (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:154:30)\n    at async getProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:314:17)\n    at async Immediate.<anonymous> (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:291:33)\n\nNode.js v20.9.0\n"
[START][2024-02-20 18:04:17] LSP logging initiated
[WARN][2024-02-20 18:04:17] ...lsp/handlers.lua:137	"The language server astro triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2024-02-20 18:04:17] .../vim/lsp/rpc.lua:734	"rpc"	"astro-ls"	"stderr"	"/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45\n                readDirectory: modules.typescript.sys.readDirectory,\n                                                  ^\n\nTypeError: Cannot read properties of undefined (reading 'sys')\n    at Object.resolveConfig (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/dist/languageServerPlugin.js:45:51)\n    at createProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/project.js:78:35)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:449:9)\n    at async getParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:302:29)\n    at async prepareClosestootParsedCommandLine (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:224:17)\n    at async findMatchConfigs (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:213:9)\n    at async Object.getProjectAndTsConfig [as getProject] (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/workspaces.js:154:30)\n    at async getProject (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:314:17)\n    at async Immediate.<anonymous> (/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/lib/common/features/languageFeatures.js:291:33)\n\nNode.js v20.9.0\n"
```

### Screenshots

![index astro-lsp-inactive-2024-02-20 19-14-02](https://github.com/LunarVim/LunarVim/assets/6347403/e4eb34ca-8a8c-407a-bf6e-6a09e30791af)

**Comment by lesar** [comment]
The bug on VSCodium is solve by [this patch](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/commit/9209a739b57bccf076e6a9d07857b6ad694eff4d)  (I believe)  

The bug is resembling to mine. I think is not a bug on astro-language-server but something on lvim/Mason installation/setup.  

I do not know where post this issue: here or somewhere else.

best regards,
Leonardo

**Comment by chase** [comment]
The problem seems to be that the `typescript` package isn't being installed along with the language server.

One way you might try to fix this is to do a global install of `typescript`. Otherwise try `(cd ~/.local/share/lvim/mason/packages/astro-language-server && npm i --no-save typescript)`.

Regardless, seems like mason isn't doing something right here.

**Comment by lesar** [comment]
thank you @chase .
I agree mason isn't doing something right here.  
if I do:  
`$ pnpm list -g`
I get:  
> Legend: production dependency, optional only, dev only
> 
> /home/leonardo/.local/share/pnpm/global/5
> 
> dependencies:
> neovim 4.10.1
> pnpm 8.15.3
> typescript 5.3.3
> typescript-language-server 4.3.3

I 
`$ cd ~/.local/share/lvim/mason/packages/astro-language-server`  
and  then do   
`$ npm i --no-save typescript`  

I can see that typescript was jast installed.  
then I do `$ ls -l node_modules/typescript/bin/`
> tsc
> tsserver

I try again lvim on my project but the error still present!  

I think that something try to find typescript on wrong local path  

best regards,
Leonardo

**Comment by olrtg** [comment]
Just in case try with `:MasonInstall astro-language-server` instead of the `:LspInstall astro` command.

**Comment by lesar** [comment]
Thank you @olrtg I have try but same error message: 
> Typescript module is missing
> assert in /usr/share/nvim/runtime/lua/vim/lsp.lua:1308: in function ''
> vim/_editor.lua: in function <vim/_editor.lua:0>

best regards
Leonardo

**Comment by olrtg** [comment]
Just curious. On which version of node are you?

**Comment by lesar** [comment]
I have:  
```
$ node -v
v20.9.0
$ pnpm -v
8.15.3
```

**Comment by olrtg** [comment]
Can you try installing typescript globally and making sure that `tsc` is on your `PATH`?

**Comment by lesar** [comment]
I have installed local and global:  
```bach
$ which tsc
~/.local/share/pnpm/tsc
$ echo $PATH
/home/leonardo/.local/share/pnpm: ...
$ find / -name tsc -not -path "/immagini/*" -not -path "/var/*" -type f -executable -print
/home/leonardo/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/typescript/bin/tsc
/home/leonardo/.local/share/lvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/typescript/bin/tsc
/home/leonardo/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/typescript/bin/tsc
/home/leonardo/.local/share/lvim/mason/packages/typescript-language-server/node_modules/typescript/bin/tsc
/home/leonardo/.local/share/lvim/mason/packages/astro-language-server/node_modules/typescript/bin/tsc
/home/leonardo/.local/share/pnpm/global/5/.pnpm/typescript@5.3.3/node_modules/typescript/bin/tsc
/home/leonardo/.local/share/pnpm/global/5/.pnpm/typescript@5.3.3/node_modules/typescript/node_modules/.bin/tsc
/home/leonardo/.local/share/pnpm/tsc
```

best regards,
Leonardo

P.S.: astro-language-server on VSCodium works

**Comment by chase** [comment]
> I have installed local and global:
> 
> ```
> $ which tsc
> ~/.local/share/pnpm/tsc
> $ echo $PATH
> /home/leonardo/.local/share/pnpm: ...

Ah, `pnpm` uses a non-standard path.
Since `lvim` doesn't use a login shell, it's likely not picking up that path.

Try adding the PATH to `lvim`'s wrapper script.
`nvim $(which lvim)`

``` diff
+ export PATH=/home/leonardo/.local/share/pnpm:$PATH

  export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/leonardo/.local/share/lunarvim"}"
```

**Comment by lesar** [comment]
thank you @chase . I try but it not work:  
```bash
#!/bin/bash
export PATH=/home/leonardo/.local/share/pnpm:$PATH
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-'/home/leonardo/.local/share/lunarvim'}"
/home/leonardo/.local/bin/lvim
exit 0
```

**Comment by maxym-rybak** [comment]
I had similar issue `root directory:    Not found.` for tailwindcss. The root of the problem is that I where using `tailwind.config.mjs` and .mjs extension is not listed in configuration.
![Screenshot 2024-03-20 at 18 20 09](https://github.com/LunarVim/LunarVim/assets/30364754/89385871-bdbb-4955-a8e6-d42140a3138e)
