### ISSUE TITLE
deno fresh warnings: "Cannot find module '@preact/signals' or its corresponding type declarations."

### ISSUE THREAD

**Issue by kirilligum** [LunarVim/LunarVim#4526]
### Problem description

fresh install of deno's webframework "Fresh" gives warnings related to preact / react

![image](https://github.com/LunarVim/LunarVim/assets/1944021/f8dc33c6-6471-4f44-a585-4529411f0a22)

### LunarVim version

master-9ee3b7b8

### Neovim version (>= 0.9.1)

NVIM v0.10.0-dev

### Operating system/version

5.15.90.1-microsoft-standard-WSL2 ubuntu

### Affected language servers

all

### Steps to reproduce

1. install lunarvim `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh`
2. install deno https://docs.deno.com/runtime/manual by running `curl -fsSL https://deno.land/install.sh | sh`
3. create a fresh project https://fresh.deno.dev/docs/getting-started/create-a-project 
```
deno run -A -r https://fresh.deno.dev
cd fresh-project
deno task start
```
4. lvim 

### Actual behavior

line 1:
```
import { useSignal } from "@preact/signals";
```
shows a warning:
```
routes/index.tsx|1 col 27-44 error| Cannot find module '@preact/signals' or its corresponding type declarations.
```

### Expected behavior

no warning

### support info

lspinfo:
![image](https://github.com/LunarVim/LunarVim/assets/1944021/b2157425-b7d1-4c12-b898-08eea9ddfc56)
lviminfo
![image](https://github.com/LunarVim/LunarVim/assets/1944021/f8adab1e-a216-4091-8a03-4d0f1b62e93f)

### logs

```console
[START][2024-03-10 20:52:43] LSP logging initiated
[WARN][2024-03-10 20:52:43] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 20:53:18] LSP logging initiated
[WARN][2024-03-10 20:53:18] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2024-03-10 20:53:18] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-03-10 20:53:18] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[ERROR][2024-03-10 20:53:18] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[WARN][2024-03-10 20:53:22] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 20:53:27] LSP logging initiated
[WARN][2024-03-10 20:53:27] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2024-03-10 20:53:27] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-03-10 20:53:27] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[ERROR][2024-03-10 20:53:27] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[START][2024-03-10 20:56:59] LSP logging initiated
[WARN][2024-03-10 20:56:59] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 21:09:32] LSP logging initiated
[WARN][2024-03-10 21:09:32] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2024-03-10 21:09:32] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-03-10 21:09:32] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[ERROR][2024-03-10 21:09:32] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[START][2024-03-10 21:10:19] LSP logging initiated
[WARN][2024-03-10 21:10:19] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2024-03-10 21:10:19] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-03-10 21:10:19] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[ERROR][2024-03-10 21:10:19] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[START][2024-03-10 21:26:40] LSP logging initiated
[WARN][2024-03-10 21:26:40] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2024-03-10 21:26:40] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-03-10 21:26:40] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[ERROR][2024-03-10 21:26:40] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[START][2024-03-10 21:27:46] LSP logging initiated
[WARN][2024-03-10 21:27:46] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 21:29:23] LSP logging initiated
[WARN][2024-03-10 21:29:23] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 21:29:50] LSP logging initiated
[WARN][2024-03-10 21:29:50] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2024-03-10 21:29:50] .../lua/vim/lsp.lua:1173	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-03-10 21:29:50] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[ERROR][2024-03-10 21:29:50] ...lsp/handlers.lua:556	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/kirill/.local/share/lvim/mason/packages/json-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21)"
[WARN][2024-03-10 21:29:55] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 21:34:24] LSP logging initiated
[WARN][2024-03-10 21:34:24] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 21:36:02] LSP logging initiated
[WARN][2024-03-10 21:36:02] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 21:37:08] LSP logging initiated
[WARN][2024-03-10 21:37:08] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 22:30:27] LSP logging initiated
[WARN][2024-03-10 22:30:27] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2024-03-10 22:32:14] LSP logging initiated
[WARN][2024-03-10 22:32:14] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/1944021/f8dc33c6-6471-4f44-a585-4529411f0a22)

**Comment by kirilligum** [comment]
running `npm install @preact/signals` removed the first warning but i feel like it is not a proper solution because even without this installation the website runs
![image](https://github.com/LunarVim/LunarVim/assets/1944021/68adb5ca-8b8d-4115-ac7f-b3c68563ec5b)

**Comment by kirilligum** [comment]
if i change the extension .tsx-->.jsx , i get lighbulbs instead of red "x"
![image](https://github.com/LunarVim/LunarVim/assets/1944021/749624e7-3fed-43e9-9e46-03d2e8d1e124)
and then the warnings disapear
![image](https://github.com/LunarVim/LunarVim/assets/1944021/e3a5e0c6-2727-401a-8f9f-9b7003ce2eb5)
